In [1]:
import pandas as pd

In [2]:
import os

In [3]:
#load the data from the local folder
file_path = '/Users/sharanya/Downloads/Raw_Data_Updated.csv' 

dataset = pd.read_csv(file_path)

print(dataset.head())

     Region Name Region Code  Year Year Code  \
0  United States         USA  2004    YR2004
1  United States         USA  2005    YR2005
2  United States         USA  2006    YR2006
3  United States         USA  2007    YR2007
4  United States         USA  2008    YR2008

  Birth rate, crude (per 1,000 people) [SP.DYN.CBRT.IN]  \
0                                                 14
1                                                 14
2                                               14.3
3                                               14.3
4                                                 14

  Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS]  \
0                                               99.3
1                                               99.4
2                                               99.4
3                                               99.3
4                                               99.3

  Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total) [SH.DTH.COMM.ZS]  \
0                                                 ..
1                                                 ..
2                                                 ..
3                                                 ..
4                                                 ..

  Death rate, crude (per 1,000 people) [SP.DYN.CDRT.IN]  \
0                                                8.2
1                                                8.3
2                                                8.1
3                                                  8
4                                                8.1

  Diabetes prevalence (% of population ages 20 to 79) [SH.STA.DIAB.ZS]  \
0                                                 ..
1                                                 ..
2                                                 ..
3                                                 ..
4                                                 ..

  Hospital beds (per 1,000 people) [SH.MED.BEDS.ZS]  ...  \
0                                              3.26  ...
1                                               3.2  ...
2                                              3.18  ...
3                                              3.14  ...
4                                              3.13  ...

  Postnatal care coverage (% mothers) [SH.STA.PNVC.ZS]  \
0                                                 ..
1                                                 ..
2                                                 ..
3                                                 ..
4                                                 ..

  Pregnant women receiving prenatal care (%) [SH.STA.ANVC.ZS]  \
0                                                 ..
1                                                 ..
2                                                 ..
3                                                 ..
4                                                 ..

  Pregnant women receiving prenatal care of at least four visits (% of pregnant women) [SH.STA.ANV4.ZS]  \
0                                                 ..
1                                                 ..
2                                                 ..
3                                                 ..
4                                                 ..

  Prevalence of anemia among pregnant women (%) [SH.PRG.ANEM]  \
0                                                9.1
1                                                9.2
2                                                9.3
3                                                9.5
4                                                9.6

  Prevalence of anemia among children (% of children ages 6-59 months) [SH.ANM.CHLD.ZS]  \
0                                                5.9
1                                                5.9
2                                                5.8
3                                                5.8
4                                                5.8

  Prevalence of current tobacco use, pregnant women (% of pregnant women adults) [SH.PRV.SMOK.FE]  \
0                                                 ..
1                                               24.2
2                                                 ..
3                                                 ..
4                                                 ..

  Prevalence of hypertension, pregnant women (% of pregnant women adults ages 30-79) [SH.HTN.PREV.FE.ZS]  \
0                                               29.9
1                                                 30
2                                                 30
3                                               30.1
4                                               30.1

  Stillbirth rate (per 1,000 total births) [SH.DYN.STLB]  \
0                                                3.1
1                                                  3
2                                                  3
3                                                  3
4                                                3.1

  Total alcohol consumption per capita (liters of pure alcohol, projected estimates, pregnant women 15+ years of age) [SH.ALC.PCAP.FE.LI]  \
0                                                 ..
1                                            4.17317
2                                                 ..
3                                                 ..
4                                                 ..

  Vitamin A supplementation coverage rate (% of children ages 6-59 months) [SN.ITK.VITA.ZS]
0                                                 ..
1                                                 ..
2                                                 ..
3                                                 ..
4                                                 ..

[5 rows x 48 columns]

In [4]:
pip install qgrid

Requirement already satisfied: qgrid in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (1.3.1)
Requirement already satisfied: notebook>=4.0.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from qgrid) (7.2.2)
Requirement already satisfied: pandas>=0.18.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from qgrid) (2.2.2)
Requirement already satisfied: ipywidgets>=7.0.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from qgrid) (8.1.5)
Requirement already satisfied: comm>=0.1.3 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ipywidgets>=7.0.0->qgrid) (0.2.2)
Requirement already satisfied: ipython>=6.1.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ipywidgets>=7.0.0->qgrid) (8.27.0)
Requirement already satisfied: traitlets>=4.3.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ipywidgets>=7.0.0->qgrid) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.12 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ipywidgets>=7.0.0->qgrid) (4.0.13)
Requirement already satisfied: jupyterlab-widgets~=3.0.12 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ipywidgets>=7.0.0->qgrid) (3.0.13)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from notebook>=4.0.0->qgrid) (2.14.2)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from notebook>=4.0.0->qgrid) (2.27.3)
Requirement already satisfied: jupyterlab<4.3,>=4.2.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from notebook>=4.0.0->qgrid) (4.2.5)
Requirement already satisfied: notebook-shim<0.3,>=0.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from notebook>=4.0.0->qgrid) (0.2.4)
Requirement already satisfied: tornado>=6.2.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from notebook>=4.0.0->qgrid) (6.4.1)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=0.18.0->qgrid) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=0.18.0->qgrid) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=0.18.0->qgrid) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=0.18.0->qgrid) (2024.1)
Requirement already satisfied: decorator in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (0.19.1)
Requirement already satisfied: matplotlib-inline in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (0.1.7)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (3.0.47)
Requirement already satisfied: pygments>=2.4.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (2.18.0)
Requirement already satisfied: stack-data in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (0.6.3)
Requirement already satisfied: pexpect>4.3 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (4.9.0)
Requirement already satisfied: anyio>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (4.4.0)
Requirement already satisfied: argon2-cffi>=21.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (23.1.0)
Requirement already satisfied: jinja2>=3.0.3 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (3.1.4)
Requirement already satisfied: jupyter-client>=7.4.4 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (8.6.2)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (5.7.2)
Requirement already satisfied: jupyter-events>=0.9.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.10.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.5.3)
Requirement already satisfied: nbconvert>=6.4.4 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (7.16.4)
Requirement already satisfied: nbformat>=5.3.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (5.10.4)
Requirement already satisfied: overrides>=5.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (7.7.0)
Requirement already satisfied: packaging>=22.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (24.1)
Requirement already satisfied: prometheus-client>=0.9 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.20.0)
Requirement already satisfied: pyzmq>=24 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (26.2.0)
Requirement already satisfied: send2trash>=1.8.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.8.0)
Requirement already satisfied: async-lru>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyterlab<4.3,>=4.2.0->notebook>=4.0.0->qgrid) (2.0.4)
Requirement already satisfied: httpx>=0.25.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyterlab<4.3,>=4.2.0->notebook>=4.0.0->qgrid) (0.27.2)
Requirement already satisfied: ipykernel>=6.5.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyterlab<4.3,>=4.2.0->notebook>=4.0.0->qgrid) (6.29.5)
Requirement already satisfied: jupyter-lsp>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyterlab<4.3,>=4.2.0->notebook>=4.0.0->qgrid) (2.2.5)
Requirement already satisfied: setuptools>=40.1.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyterlab<4.3,>=4.2.0->notebook>=4.0.0->qgrid) (74.1.2)
Requirement already satisfied: babel>=2.10 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyterlab-server<3,>=2.27.1->notebook>=4.0.0->qgrid) (2.16.0)
Requirement already satisfied: json5>=0.9.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyterlab-server<3,>=2.27.1->notebook>=4.0.0->qgrid) (0.9.25)
Requirement already satisfied: jsonschema>=4.18.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyterlab-server<3,>=2.27.1->notebook>=4.0.0->qgrid) (4.23.0)
Requirement already satisfied: requests>=2.31 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyterlab-server<3,>=2.27.1->notebook>=4.0.0->qgrid) (2.32.3)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=0.18.0->qgrid) (1.16.0)
Requirement already satisfied: idna>=2.8 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (3.8)
Requirement already satisfied: sniffio>=1.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.3.1)
Requirement already satisfied: argon2-cffi-bindings in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (21.2.0)
Requirement already satisfied: certifi in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from httpx>=0.25.0->jupyterlab<4.3,>=4.2.0->notebook>=4.0.0->qgrid) (2024.8.30)
Requirement already satisfied: httpcore==1.* in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from httpx>=0.25.0->jupyterlab<4.3,>=4.2.0->notebook>=4.0.0->qgrid) (1.0.5)
Requirement already satisfied: h11<0.15,>=0.13 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab<4.3,>=4.2.0->notebook>=4.0.0->qgrid) (0.14.0)
Requirement already satisfied: appnope in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ipykernel>=6.5.0->jupyterlab<4.3,>=4.2.0->notebook>=4.0.0->qgrid) (0.1.4)
Requirement already satisfied: debugpy>=1.6.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ipykernel>=6.5.0->jupyterlab<4.3,>=4.2.0->notebook>=4.0.0->qgrid) (1.8.5)
Requirement already satisfied: nest-asyncio in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ipykernel>=6.5.0->jupyterlab<4.3,>=4.2.0->notebook>=4.0.0->qgrid) (1.6.0)
Requirement already satisfied: psutil in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ipykernel>=6.5.0->jupyterlab<4.3,>=4.2.0->notebook>=4.0.0->qgrid) (6.0.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (0.8.4)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jinja2>=3.0.3->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (2.1.5)
Requirement already satisfied: attrs>=22.2.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook>=4.0.0->qgrid) (24.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook>=4.0.0->qgrid) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook>=4.0.0->qgrid) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook>=4.0.0->qgrid) (0.20.0)
Requirement already satisfied: platformdirs>=2.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (4.3.2)
Requirement already satisfied: python-json-logger>=2.0.4 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (2.0.7)
Requirement already satisfied: pyyaml>=5.3 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (6.0.2)
Requirement already satisfied: rfc3339-validator in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.1.1)
Requirement already satisfied: beautifulsoup4 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (4.12.3)
Requirement already satisfied: bleach!=5.0.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (6.1.0)
Requirement already satisfied: defusedxml in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (3.0.2)
Requirement already satisfied: nbclient>=0.5.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.10.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.5.1)
Requirement already satisfied: tinycss2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.3.0)
Requirement already satisfied: fastjsonschema>=2.15 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (2.20.0)
Requirement already satisfied: ptyprocess>=0.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (0.7.0)
Requirement already satisfied: wcwidth in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (0.2.13)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->notebook>=4.0.0->qgrid) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->notebook>=4.0.0->qgrid) (2.2.3)
Requirement already satisfied: executing>=1.2.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (2.1.0)
Requirement already satisfied: asttokens>=2.1.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (2.4.1)
Requirement already satisfied: pure-eval in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (0.2.3)
Requirement already satisfied: webencodings in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from bleach!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.5.1)
Requirement already satisfied: fqdn in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.5.1)
Requirement already satisfied: isoduration in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (3.0.0)
Requirement already satisfied: uri-template in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (24.8.0)
Requirement already satisfied: cffi>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.17.1)
Requirement already satisfied: soupsieve>1.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (2.6)
Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (2.22)
Requirement already satisfied: arrow>=0.15.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.3.0)
Requirement already satisfied: types-python-dateutil>=2.8.10 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (2.9.0.20240906)

In [5]:
#Data Cleaning
#Step 1 :  Remove duplicates rows

dataset.drop_duplicates(keep='first', inplace=True)

file_path = '/Users/sharanya/Downloads/Remove_Duplicate_Rows.csv' 
dataset.to_csv(file_path, index=False)
dataset.head()

,Region Name,Region Code,Year,Year Code,"Birth rate, crude (per 1,000 people) [SP.DYN.CBRT.IN]",Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS],"Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total) [SH.DTH.COMM.ZS]","Death rate, crude (per 1,000 people) [SP.DYN.CDRT.IN]",Diabetes prevalence (% of population ages 20 to 79) [SH.STA.DIAB.ZS],"Hospital beds (per 1,000 people) [SH.MED.BEDS.ZS]",...,Postnatal care coverage (% mothers) [SH.STA.PNVC.ZS],Pregnant women receiving prenatal care (%) [SH.STA.ANVC.ZS],Pregnant women receiving prenatal care of at least four visits (% of pregnant women) [SH.STA.ANV4.ZS],Prevalence of anemia among pregnant women (%) [SH.PRG.ANEM],Prevalence of anemia among children (% of children ages 6-59 months) [SH.ANM.CHLD.ZS],"Prevalence of current tobacco use, pregnant women (% of pregnant women adults) [SH.PRV.SMOK.FE]","Prevalence of hypertension, pregnant women (% of pregnant women adults ages 30-79) [SH.HTN.PREV.FE.ZS]","Stillbirth rate (per 1,000 total births) [SH.DYN.STLB]","Total alcohol consumption per capita (liters of pure alcohol, projected estimates, pregnant women 15+ years of age) [SH.ALC.PCAP.FE.LI]",Vitamin A supplementation coverage rate (% of children ages 6-59 months) [SN.ITK.VITA.ZS]
0,United States,USA,2004,YR2004,14,99.3,..,8.2,..,3.26,...,..,..,..,9.1,5.9,..,29.9,3.1,..,..
1,United States,USA,2005,YR2005,14,99.4,..,8.3,..,3.2,...,..,..,..,9.2,5.9,24.2,30,3,4.17317,..
2,United States,USA,2006,YR2006,14.3,99.4,..,8.1,..,3.18,...,..,..,..,9.3,5.8,..,30,3,..,..
3,United States,USA,2007,YR2007,14.3,99.3,..,8,..,3.14,...,..,..,..,9.5,5.8,..,30.1,3,..,..
4,United States,USA,2008,YR2008,14,99.3,..,8.1,..,3.13,...,..,..,..,9.6,5.8,..,30.1,3.1,..,..

In [6]:
#Data Cleaning
#Step 2 : Remove irrelevant column like Year Code
print(dataset.columns)
dataset.columns = dataset.columns.str.strip()
dataset.drop(columns=['Year Code'], errors='ignore', inplace=True)
for col in dataset.columns:
    print(col)

file_path = '~/Downloads/remove_irrelevant_columns_dataset.csv'
dataset.to_csv(file_path, index=False)

Index(['Region Name', 'Region Code', 'Year', 'Year Code',
       'Birth rate, crude (per 1,000 people) [SP.DYN.CBRT.IN]',
       'Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS]',
       'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total) [SH.DTH.COMM.ZS]',
       'Death rate, crude (per 1,000 people) [SP.DYN.CDRT.IN]',
       'Diabetes prevalence (% of population ages 20 to 79) [SH.STA.DIAB.ZS]',
       'Hospital beds (per 1,000 people) [SH.MED.BEDS.ZS]',
       'Immunization, BCG (% of one-year-old children) [SH.IMM.IBCG]',
       'Immunization, HepB3 (% of one-year-old children) [SH.IMM.HEPB]',
       'Immunization, measles second dose (% of children by the nationally recommended age) [SH.IMM.MEA2]',
       'Immunization, Pol3 (% of one-year-old children) [SH.IMM.POL3]',
       'Intermittent preventive treatment (IPT) of malaria in pregnancy (% of pregnant women) [SH.MLR.IPTP.ZS]',
       'Life expectancy at birth, female (years) [SP.DYN.LE00.FE.IN]',
       'Life expectancy at birth, male (years) [SP.DYN.LE00.MA.IN]',
       'Life expectancy at birth, total (years) [SP.DYN.LE00.IN]',
       'Lifetime risk of maternal death (%) [SH.MMR.RISK.ZS]',
       'Lifetime risk of maternal death (1 in: rate varies by country) [SH.MMR.RISK]',
       'Literacy rate, Pregnant Women (% of pregnant women ages 15 and above) [SE.ADT.LITR.FE.ZS]',
       'Literacy rate, adult total (% of people ages 15 and above) [SE.ADT.LITR.ZS]',
       'Low-birthweight babies (% of births) [SH.STA.BRTW.ZS]',
       'Maternal mortality ratio (modeled estimate, per 100,000 live births) [SH.STA.MMRT]',
       'Maternal mortality ratio (national estimate, per 100,000 live births) [SH.STA.MMRT.NE]',
       'Mortality rate, infant (per 1,000 live births) [SP.DYN.IMRT.IN]',
       'Mortality rate, infant, female (per 1,000 live births) [SP.DYN.IMRT.FE.IN]',
       'Mortality rate, infant, male (per 1,000 live births) [SP.DYN.IMRT.MA.IN]',
       'Mortality rate, neonatal (per 1,000 live births) [SH.DYN.NMRT]',
       'Newborns protected against tetanus (%) [SH.VAC.TTNS.ZS]',
       'Number of infant deaths [SH.DTH.IMRT]',
       'Number of infant deaths, female [SH.DTH.IMRT.FE]',
       'Number of infant deaths, male [SH.DTH.IMRT.MA]',
       'Number of maternal deaths [SH.MMR.DTHS]',
       'Number of neonatal deaths [SH.DTH.NMRT]',
       'Number of stillbirths [SH.DTH.STLB]',
       'Nurses and midwives (per 1,000 people) [SH.MED.NUMW.P3]',
       'Physicians (per 1,000 people) [SH.MED.PHYS.ZS]',
       'Postnatal care coverage (% mothers) [SH.STA.PNVC.ZS]',
       'Pregnant women receiving prenatal care (%) [SH.STA.ANVC.ZS]',
       'Pregnant women receiving prenatal care of at least four visits (% of pregnant women) [SH.STA.ANV4.ZS]',
       'Prevalence of anemia among pregnant women (%) [SH.PRG.ANEM]',
       'Prevalence of anemia among children (% of children ages 6-59 months) [SH.ANM.CHLD.ZS]',
       'Prevalence of current tobacco use, pregnant women (% of pregnant women adults) [SH.PRV.SMOK.FE]',
       'Prevalence of hypertension, pregnant women (% of pregnant women adults ages 30-79) [SH.HTN.PREV.FE.ZS]',
       'Stillbirth rate (per 1,000 total births) [SH.DYN.STLB]',
       'Total alcohol consumption per capita (liters of pure alcohol, projected estimates, pregnant women 15+ years of age) [SH.ALC.PCAP.FE.LI]',
       'Vitamin A supplementation coverage rate (% of children ages 6-59 months) [SN.ITK.VITA.ZS]'],
      dtype='object')
Region Name
Region Code
Year
Birth rate, crude (per 1,000 people) [SP.DYN.CBRT.IN]
Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS]
Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total) [SH.DTH.COMM.ZS]
Death rate, crude (per 1,000 people) [SP.DYN.CDRT.IN]
Diabetes prevalence (% of population ages 20 to 79) [SH.STA.DIAB.ZS]
Hospital beds (per 1,000 people) [SH.MED.BEDS.ZS]
Immunization, BCG (% of one-year-old children) [SH.IMM.IBCG]
Immunization, HepB3 (% of one-year-old children) [SH.IMM.HEPB]
Immunization, measles second dose (% of children by the nationally recommended age) [SH.IMM.MEA2]
Immunization, Pol3 (% of one-year-old children) [SH.IMM.POL3]
Intermittent preventive treatment (IPT) of malaria in pregnancy (% of pregnant women) [SH.MLR.IPTP.ZS]
Life expectancy at birth, female (years) [SP.DYN.LE00.FE.IN]
Life expectancy at birth, male (years) [SP.DYN.LE00.MA.IN]
Life expectancy at birth, total (years) [SP.DYN.LE00.IN]
Lifetime risk of maternal death (%) [SH.MMR.RISK.ZS]
Lifetime risk of maternal death (1 in: rate varies by country) [SH.MMR.RISK]
Literacy rate, Pregnant Women (% of pregnant women ages 15 and above) [SE.ADT.LITR.FE.ZS]
Literacy rate, adult total (% of people ages 15 and above) [SE.ADT.LITR.ZS]
Low-birthweight babies (% of births) [SH.STA.BRTW.ZS]
Maternal mortality ratio (modeled estimate, per 100,000 live births) [SH.STA.MMRT]
Maternal mortality ratio (national estimate, per 100,000 live births) [SH.STA.MMRT.NE]
Mortality rate, infant (per 1,000 live births) [SP.DYN.IMRT.IN]
Mortality rate, infant, female (per 1,000 live births) [SP.DYN.IMRT.FE.IN]
Mortality rate, infant, male (per 1,000 live births) [SP.DYN.IMRT.MA.IN]
Mortality rate, neonatal (per 1,000 live births) [SH.DYN.NMRT]
Newborns protected against tetanus (%) [SH.VAC.TTNS.ZS]
Number of infant deaths [SH.DTH.IMRT]
Number of infant deaths, female [SH.DTH.IMRT.FE]
Number of infant deaths, male [SH.DTH.IMRT.MA]
Number of maternal deaths [SH.MMR.DTHS]
Number of neonatal deaths [SH.DTH.NMRT]
Number of stillbirths [SH.DTH.STLB]
Nurses and midwives (per 1,000 people) [SH.MED.NUMW.P3]
Physicians (per 1,000 people) [SH.MED.PHYS.ZS]
Postnatal care coverage (% mothers) [SH.STA.PNVC.ZS]
Pregnant women receiving prenatal care (%) [SH.STA.ANVC.ZS]
Pregnant women receiving prenatal care of at least four visits (% of pregnant women) [SH.STA.ANV4.ZS]
Prevalence of anemia among pregnant women (%) [SH.PRG.ANEM]
Prevalence of anemia among children (% of children ages 6-59 months) [SH.ANM.CHLD.ZS]
Prevalence of current tobacco use, pregnant women (% of pregnant women adults) [SH.PRV.SMOK.FE]
Prevalence of hypertension, pregnant women (% of pregnant women adults ages 30-79) [SH.HTN.PREV.FE.ZS]
Stillbirth rate (per 1,000 total births) [SH.DYN.STLB]
Total alcohol consumption per capita (liters of pure alcohol, projected estimates, pregnant women 15+ years of age) [SH.ALC.PCAP.FE.LI]
Vitamin A supplementation coverage rate (% of children ages 6-59 months) [SN.ITK.VITA.ZS]

In [7]:
#Data Cleaning
#Step 3 : Remove irrelevant data

unwanted_regions = [ '', 'Fragile and conflict affected situations', 'Heavily indebted poor countries (HIPC)', 'High income', 'IBRD only', 'IDA & IBRD total', 'IDA blend', 'IDA only', 'IDA total', 'Late-demographic dividend', 'Early-demographic dividend', 'Post-demographic dividend', 'Pre-demographic dividend', 'Low & middle income', 'Least developed countries: UN classification', 'Low income', 'Lower middle income', 'Not classified', 'OECD members', 'Other small states', 'South Asia (IDA & IBRD)', 'Upper middle income', 'World' ]

dataset_cleaned = dataset[~dataset['Region Name'].isin(unwanted_regions)] 

file_path = '~/Downloads/remove_rows_unwanted_regions_dataset.csv'
dataset_cleaned.to_csv(file_path, index=False)

dataset_cleaned.head()

,Region Name,Region Code,Year,"Birth rate, crude (per 1,000 people) [SP.DYN.CBRT.IN]",Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS],"Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total) [SH.DTH.COMM.ZS]","Death rate, crude (per 1,000 people) [SP.DYN.CDRT.IN]",Diabetes prevalence (% of population ages 20 to 79) [SH.STA.DIAB.ZS],"Hospital beds (per 1,000 people) [SH.MED.BEDS.ZS]","Immunization, BCG (% of one-year-old children) [SH.IMM.IBCG]",...,Postnatal care coverage (% mothers) [SH.STA.PNVC.ZS],Pregnant women receiving prenatal care (%) [SH.STA.ANVC.ZS],Pregnant women receiving prenatal care of at least four visits (% of pregnant women) [SH.STA.ANV4.ZS],Prevalence of anemia among pregnant women (%) [SH.PRG.ANEM],Prevalence of anemia among children (% of children ages 6-59 months) [SH.ANM.CHLD.ZS],"Prevalence of current tobacco use, pregnant women (% of pregnant women adults) [SH.PRV.SMOK.FE]","Prevalence of hypertension, pregnant women (% of pregnant women adults ages 30-79) [SH.HTN.PREV.FE.ZS]","Stillbirth rate (per 1,000 total births) [SH.DYN.STLB]","Total alcohol consumption per capita (liters of pure alcohol, projected estimates, pregnant women 15+ years of age) [SH.ALC.PCAP.FE.LI]",Vitamin A supplementation coverage rate (% of children ages 6-59 months) [SN.ITK.VITA.ZS]
0,United States,USA,2004,14,99.3,..,8.2,..,3.26,..,...,..,..,..,9.1,5.9,..,29.9,3.1,..,..
1,United States,USA,2005,14,99.4,..,8.3,..,3.2,..,...,..,..,..,9.2,5.9,24.2,30,3,4.17317,..
2,United States,USA,2006,14.3,99.4,..,8.1,..,3.18,..,...,..,..,..,9.3,5.8,..,30,3,..,..
3,United States,USA,2007,14.3,99.3,..,8,..,3.14,..,...,..,..,..,9.5,5.8,..,30.1,3,..,..
4,United States,USA,2008,14,99.3,..,8.1,..,3.13,..,...,..,..,..,9.6,5.8,..,30.1,3.1,..,..

In [8]:
print(dataset_cleaned.columns)

Index(['Region Name', 'Region Code', 'Year',
       'Birth rate, crude (per 1,000 people) [SP.DYN.CBRT.IN]',
       'Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS]',
       'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total) [SH.DTH.COMM.ZS]',
       'Death rate, crude (per 1,000 people) [SP.DYN.CDRT.IN]',
       'Diabetes prevalence (% of population ages 20 to 79) [SH.STA.DIAB.ZS]',
       'Hospital beds (per 1,000 people) [SH.MED.BEDS.ZS]',
       'Immunization, BCG (% of one-year-old children) [SH.IMM.IBCG]',
       'Immunization, HepB3 (% of one-year-old children) [SH.IMM.HEPB]',
       'Immunization, measles second dose (% of children by the nationally recommended age) [SH.IMM.MEA2]',
       'Immunization, Pol3 (% of one-year-old children) [SH.IMM.POL3]',
       'Intermittent preventive treatment (IPT) of malaria in pregnancy (% of pregnant women) [SH.MLR.IPTP.ZS]',
       'Life expectancy at birth, female (years) [SP.DYN.LE00.FE.IN]',
       'Life expectancy at birth, male (years) [SP.DYN.LE00.MA.IN]',
       'Life expectancy at birth, total (years) [SP.DYN.LE00.IN]',
       'Lifetime risk of maternal death (%) [SH.MMR.RISK.ZS]',
       'Lifetime risk of maternal death (1 in: rate varies by country) [SH.MMR.RISK]',
       'Literacy rate, Pregnant Women (% of pregnant women ages 15 and above) [SE.ADT.LITR.FE.ZS]',
       'Literacy rate, adult total (% of people ages 15 and above) [SE.ADT.LITR.ZS]',
       'Low-birthweight babies (% of births) [SH.STA.BRTW.ZS]',
       'Maternal mortality ratio (modeled estimate, per 100,000 live births) [SH.STA.MMRT]',
       'Maternal mortality ratio (national estimate, per 100,000 live births) [SH.STA.MMRT.NE]',
       'Mortality rate, infant (per 1,000 live births) [SP.DYN.IMRT.IN]',
       'Mortality rate, infant, female (per 1,000 live births) [SP.DYN.IMRT.FE.IN]',
       'Mortality rate, infant, male (per 1,000 live births) [SP.DYN.IMRT.MA.IN]',
       'Mortality rate, neonatal (per 1,000 live births) [SH.DYN.NMRT]',
       'Newborns protected against tetanus (%) [SH.VAC.TTNS.ZS]',
       'Number of infant deaths [SH.DTH.IMRT]',
       'Number of infant deaths, female [SH.DTH.IMRT.FE]',
       'Number of infant deaths, male [SH.DTH.IMRT.MA]',
       'Number of maternal deaths [SH.MMR.DTHS]',
       'Number of neonatal deaths [SH.DTH.NMRT]',
       'Number of stillbirths [SH.DTH.STLB]',
       'Nurses and midwives (per 1,000 people) [SH.MED.NUMW.P3]',
       'Physicians (per 1,000 people) [SH.MED.PHYS.ZS]',
       'Postnatal care coverage (% mothers) [SH.STA.PNVC.ZS]',
       'Pregnant women receiving prenatal care (%) [SH.STA.ANVC.ZS]',
       'Pregnant women receiving prenatal care of at least four visits (% of pregnant women) [SH.STA.ANV4.ZS]',
       'Prevalence of anemia among pregnant women (%) [SH.PRG.ANEM]',
       'Prevalence of anemia among children (% of children ages 6-59 months) [SH.ANM.CHLD.ZS]',
       'Prevalence of current tobacco use, pregnant women (% of pregnant women adults) [SH.PRV.SMOK.FE]',
       'Prevalence of hypertension, pregnant women (% of pregnant women adults ages 30-79) [SH.HTN.PREV.FE.ZS]',
       'Stillbirth rate (per 1,000 total births) [SH.DYN.STLB]',
       'Total alcohol consumption per capita (liters of pure alcohol, projected estimates, pregnant women 15+ years of age) [SH.ALC.PCAP.FE.LI]',
       'Vitamin A supplementation coverage rate (% of children ages 6-59 months) [SN.ITK.VITA.ZS]'],
      dtype='object')

In [9]:
#Data Cleaning
#Step 4 : Remove Missing Data

placeholder_value = ".."

# Calculate the threshold for dropping columns
threshold_80 = len(dataset_cleaned) * 0.8  # 80% threshold

# Remove columns where the count of placeholder values is greater than 80%
dataset_cleaned2 = dataset_cleaned.loc[:, dataset_cleaned.apply(lambda col: (col == placeholder_value).sum() <= threshold_80)]

# Display the cleaned DataFrame
print(dataset_cleaned2)

file_path = '~/Downloads/remove_missing_data.csv'
dataset_cleaned2.to_csv(file_path, index=False)

original_columns = set(dataset_cleaned.columns)

cleaned_columns = set(dataset_cleaned2.columns)

dropped_columns = original_columns - cleaned_columns

print("Dropped columns are listed below:", dropped_columns)

        Region Name Region Code  Year  \
0     United States         USA  2004
1     United States         USA  2005
2     United States         USA  2006
3     United States         USA  2007
4     United States         USA  2008
...             ...         ...   ...
5324       Zimbabwe         ZWE  2019
5325       Zimbabwe         ZWE  2020
5326       Zimbabwe         ZWE  2021
5327       Zimbabwe         ZWE  2022
5328       Zimbabwe         ZWE  2023

     Birth rate, crude (per 1,000 people) [SP.DYN.CBRT.IN]  \
0                                                    14
1                                                    14
2                                                  14.3
3                                                  14.3
4                                                    14
...                                                 ...
5324                                             31.518
5325                                             31.009
5326                                             30.537
5327                                             30.086
5328                                                 ..

     Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS]  \
0                                                  99.3
1                                                  99.4
2                                                  99.4
3                                                  99.3
4                                                  99.3
...                                                 ...
5324                                                 86
5325                                                 ..
5326                                                 ..
5327                                                 ..
5328                                                 ..

     Death rate, crude (per 1,000 people) [SP.DYN.CDRT.IN]  \
0                                                   8.2
1                                                   8.3
2                                                   8.1
3                                                     8
4                                                   8.1
...                                                 ...
5324                                              8.043
5325                                              8.132
5326                                              9.057
5327                                              8.943
5328                                                 ..

     Hospital beds (per 1,000 people) [SH.MED.BEDS.ZS]  \
0                                                 3.26
1                                                  3.2
2                                                 3.18
3                                                 3.14
4                                                 3.13
...                                                ...
5324                                                ..
5325                                                ..
5326                                                ..
5327                                                ..
5328                                                ..

     Immunization, BCG (% of one-year-old children) [SH.IMM.IBCG]  \
0                                                    ..
1                                                    ..
2                                                    ..
3                                                    ..
4                                                    ..
...                                                 ...
5324                                                 95
5325                                                 88
5326                                                 88
5327                                                 96
5328                                                 ..

     Immunization, HepB3 (% of one-year-old children) [SH.IMM.HEPB]  \
0                                                    92
1                                                    93
2                                                    93
3                                                    93
4                                                    94
...                                                 ...
5324                                                 90
5325                                                 86
5326                                                 88
5327                                                 90
5328                                                 ..

     Immunization, measles second dose (% of children by the nationally recommended age) [SH.IMM.MEA2]  \
0                                                    86
1                                                    86
2                                                    86
3                                                    86
4                                                    87
...                                                 ...
5324                                                 75
5325                                                 74
5326                                                 76
5327                                                 77
5328                                                 ..

      ... Number of neonatal deaths [SH.DTH.NMRT]  \
0     ...                                   18738
1     ...                                   18569
2     ...                                   18817
3     ...                                   18769
4     ...                                   18139
...   ...                                     ...
5324  ...                                   12589
5325  ...                                   12350
5326  ...                                   12140
5327  ...                                   11913
5328  ...                                      ..

     Number of stillbirths [SH.DTH.STLB]  \
0                                  12822
1                                  12462
2                                  12699
3                                  12965
4                                  13204
...                                  ...
5324                                8426
5325                                9235
5326                                9711
5327                                  ..
5328                                  ..

     Nurses and midwives (per 1,000 people) [SH.MED.NUMW.P3]  \
0                                                    ..
1                                                9.9177
2                                                    ..
3                                                    ..
4                                                    ..
...                                                 ...
5324                                                 ..
5325                                              2.029
5326                                                 ..
5327                                                 ..
5328                                                 ..

     Physicians (per 1,000 people) [SH.MED.PHYS.ZS]  \
0                                               2.7
1                                                ..
2                                                ..
3                                                ..
4                                                ..
...                                             ...
5324                                             ..
5325                                          0.189
5326                                             ..
5327                                             ..
5328                                             ..

     Prevalence of anemia among pregnant women (%) [SH.PRG.ANEM]  \
0                                                   9.1
1                                                   9.2
2                                                   9.3
3                                                   9.5
4                                                   9.6
...                                                 ...
5324                                               31.7
5325                                                 ..
5326                                                 ..
5327                                                 ..
5328                                                 ..

     Prevalence of anemia among children (% of children ages 6-59 months) [SH.ANM.CHLD.ZS]  \
0                                                   5.9
1                                                   5.9
2                                                   5.8
3                                                   5.8
4                                                   5.8
...                                                 ...
5324                                               37.8
5325                                                 ..
5326                                                 ..
5327                                                 ..
5328                                                 ..

     Prevalence of current tobacco use, pregnant women (% of pregnant women adults) [SH.PRV.SMOK.FE]  \
0                                                    ..
1                                                  24.2
2                                                    ..
3                                                    ..
4                                                    ..
...                                                 ...
5324                                                1.6
5325                                                1.5
5326                                                 ..
5327                                                 ..
5328                                                 ..

     Prevalence of hypertension, pregnant women (% of pregnant women adults ages 30-79) [SH.HTN.PREV.FE.ZS]  \
0                                                  29.9
1                                                    30
2                                                    30
3                                                  30.1
4                                                  30.1
...                                                 ...
5324                                               46.4
5325                                                 ..
5326                                                 ..
5327                                                 ..
5328                                                 ..

     Stillbirth rate (per 1,000 total births) [SH.DYN.STLB]  \
0                                                   3.1
1                                                     3
2                                                     3
3                                                     3
4                                                   3.1
...                                                 ...
5324                                               17.1
5325                                               18.6
5326                                               19.5
5327                                                 ..
5328                                                 ..

     Vitamin A supplementation coverage rate (% of children ages 6-59 months) [SN.ITK.VITA.ZS]
0                                                    ..
1                                                    ..
2                                                    ..
3                                                    ..
4                                                    ..
...                                                 ...
5324                                                 44
5325                                                 29
5326                                                 16
5327                                                 68
5328                                                 ..

[4882 rows x 40 columns]
Dropped columns are listed below: {'Postnatal care coverage (% mothers) [SH.STA.PNVC.ZS]', 'Total alcohol consumption per capita (liters of pure alcohol, projected estimates, pregnant women 15+ years of age) [SH.ALC.PCAP.FE.LI]', 'Pregnant women receiving prenatal care of at least four visits (% of pregnant women) [SH.STA.ANV4.ZS]', 'Pregnant women receiving prenatal care (%) [SH.STA.ANVC.ZS]', 'Diabetes prevalence (% of population ages 20 to 79) [SH.STA.DIAB.ZS]', 'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total) [SH.DTH.COMM.ZS]', 'Intermittent preventive treatment (IPT) of malaria in pregnancy (% of pregnant women) [SH.MLR.IPTP.ZS]'}

In [10]:
replacements_tracker = pd.DataFrame(False, index=dataset_cleaned2.index, columns=dataset_cleaned2.columns)

# Data Cleaning 
#Step 5
for col in dataset_cleaned2.columns:
    # Identify cells with ".."
    mask = (dataset_cleaned2[col] == "..")
    total_count = len(dataset_cleaned2[col])
    missing_count = mask.sum()
    
    missing_percentage = missing_count / total_count

    if missing_percentage > 0.5:
        # Replace ".." with 0 for columns with >50% missing values
        dataset_cleaned2[col].replace("..", 0, inplace=True)
        replacements_tracker[col] = mask
    elif missing_percentage > 0:
        # Replace ".." with mean for columns with <=50% missing values
        dataset_cleaned2[col] = pd.to_numeric(dataset_cleaned2[col], errors='coerce')
        col_mean = dataset_cleaned2[col].mean(skipna=True)
        dataset_cleaned2[col].replace("..", col_mean, inplace=True)
        replacements_tracker[col] = mask

dataset_cleaned2.to_csv('cleaned_dataset_updated.csv', index=False)

replaced_rows = replacements_tracker.any(axis=1)
print("\nRows where '..' was replaced with a value:")
print(dataset_cleaned2[replaced_rows])

Rows where '..' was replaced with a value:
        Region Name Region Code  Year  \
0     United States         USA  2004
1     United States         USA  2005
2     United States         USA  2006
3     United States         USA  2007
4     United States         USA  2008
...             ...         ...   ...
5324       Zimbabwe         ZWE  2019
5325       Zimbabwe         ZWE  2020
5326       Zimbabwe         ZWE  2021
5327       Zimbabwe         ZWE  2022
5328       Zimbabwe         ZWE  2023

      Birth rate, crude (per 1,000 people) [SP.DYN.CBRT.IN]  \
0                                                14.000
1                                                14.000
2                                                14.300
3                                                14.300
4                                                14.000
...                                                 ...
5324                                             31.518
5325                                             31.009
5326                                             30.537
5327                                             30.086
5328                                                NaN

     Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS]  \
0                                                  99.3
1                                                  99.4
2                                                  99.4
3                                                  99.3
4                                                  99.3
...                                                 ...
5324                                                 86
5325                                                  0
5326                                                  0
5327                                                  0
5328                                                  0

      Death rate, crude (per 1,000 people) [SP.DYN.CDRT.IN]  \
0                                                 8.200
1                                                 8.300
2                                                 8.100
3                                                 8.000
4                                                 8.100
...                                                 ...
5324                                              8.043
5325                                              8.132
5326                                              9.057
5327                                              8.943
5328                                                NaN

     Hospital beds (per 1,000 people) [SH.MED.BEDS.ZS]  \
0                                                 3.26
1                                                  3.2
2                                                 3.18
3                                                 3.14
4                                                 3.13
...                                                ...
5324                                                 0
5325                                                 0
5326                                                 0
5327                                                 0
5328                                                 0

      Immunization, BCG (% of one-year-old children) [SH.IMM.IBCG]  \
0                                                   NaN
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                                                   NaN
...                                                 ...
5324                                               95.0
5325                                               88.0
5326                                               88.0
5327                                               96.0
5328                                                NaN

      Immunization, HepB3 (% of one-year-old children) [SH.IMM.HEPB]  \
0                                                  92.0
1                                                  93.0
2                                                  93.0
3                                                  93.0
4                                                  94.0
...                                                 ...
5324                                               90.0
5325                                               86.0
5326                                               88.0
5327                                               90.0
5328                                                NaN

      Immunization, measles second dose (% of children by the nationally recommended age) [SH.IMM.MEA2]  \
0                                                  86.0
1                                                  86.0
2                                                  86.0
3                                                  86.0
4                                                  87.0
...                                                 ...
5324                                               75.0
5325                                               74.0
5326                                               76.0
5327                                               77.0
5328                                                NaN

      ...  Number of neonatal deaths [SH.DTH.NMRT]  \
0     ...                                  18738.0
1     ...                                  18569.0
2     ...                                  18817.0
3     ...                                  18769.0
4     ...                                  18139.0
...   ...                                      ...
5324  ...                                  12589.0
5325  ...                                  12350.0
5326  ...                                  12140.0
5327  ...                                  11913.0
5328  ...                                      NaN

      Number of stillbirths [SH.DTH.STLB]  \
0                                 12822.0
1                                 12462.0
2                                 12699.0
3                                 12965.0
4                                 13204.0
...                                   ...
5324                               8426.0
5325                               9235.0
5326                               9711.0
5327                                  NaN
5328                                  NaN

      Nurses and midwives (per 1,000 people) [SH.MED.NUMW.P3]  \
0                                                     0
1                                                9.9177
2                                                     0
3                                                     0
4                                                     0
...                                                 ...
5324                                                  0
5325                                              2.029
5326                                                  0
5327                                                  0
5328                                                  0

      Physicians (per 1,000 people) [SH.MED.PHYS.ZS]  \
0                                                2.7
1                                                  0
2                                                  0
3                                                  0
4                                                  0
...                                              ...
5324                                               0
5325                                           0.189
5326                                               0
5327                                               0
5328                                               0

      Prevalence of anemia among pregnant women (%) [SH.PRG.ANEM]  \
0                                                   9.1
1                                                   9.2
2                                                   9.3
3                                                   9.5
4                                                   9.6
...                                                 ...
5324                                               31.7
5325                                                NaN
5326                                                NaN
5327                                                NaN
5328                                                NaN

      Prevalence of anemia among children (% of children ages 6-59 months) [SH.ANM.CHLD.ZS]  \
0                                                   5.9
1                                                   5.9
2                                                   5.8
3                                                   5.8
4                                                   5.8
...                                                 ...
5324                                               37.8
5325                                                NaN
5326                                                NaN
5327                                                NaN
5328                                                NaN

     Prevalence of current tobacco use, pregnant women (% of pregnant women adults) [SH.PRV.SMOK.FE]  \
0                                                     0
1                                                  24.2
2                                                     0
3                                                     0
4                                                     0
...                                                 ...
5324                                                1.6
5325                                                1.5
5326                                                  0
5327                                                  0
5328                                                  0

     Prevalence of hypertension, pregnant women (% of pregnant women adults ages 30-79) [SH.HTN.PREV.FE.ZS]  \
0                                                  29.9
1                                                  30.0
2                                                  30.0
3                                                  30.1
4                                                  30.1
...                                                 ...
5324                                               46.4
5325                                                NaN
5326                                                NaN
5327                                                NaN
5328                                                NaN

      Stillbirth rate (per 1,000 total births) [SH.DYN.STLB]  \
0                                                   3.1
1                                                   3.0
2                                                   3.0
3                                                   3.0
4                                                   3.1
...                                                 ...
5324                                               17.1
5325                                               18.6
5326                                               19.5
5327                                                NaN
5328                                                NaN

      Vitamin A supplementation coverage rate (% of children ages 6-59 months) [SN.ITK.VITA.ZS]
0                                                     0
1                                                     0
2                                                     0
3                                                     0
4                                                     0
...                                                 ...
5324                                                 44
5325                                                 29
5326                                                 16
5327                                                 68
5328                                                  0

[4882 rows x 40 columns]

/var/folders/cl/trqdqljx2hjfbxn58ysk0cyh0000gn/T/ipykernel_72175/175144503.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_cleaned2[col] = pd.to_numeric(dataset_cleaned2[col], errors='coerce')
/var/folders/cl/trqdqljx2hjfbxn58ysk0cyh0000gn/T/ipykernel_72175/175144503.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset_cleaned2[col].replace("..", col_mean, inplace=True)
/var/folders/cl/trqdqljx2hjfbxn58ysk0cyh0000gn/T/ipykernel_72175/175144503.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_cleaned2[col].replace("..", col_mean, inplace=True)
/var/folders/cl/trqdqljx2hjfbxn58ysk0cyh0000gn/T/ipykernel_72175/175144503.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset_cleaned2[col].replace("..", 0, inplace=True)
/var/folders/cl/trqdqljx2hjfbxn58ysk0cyh0000gn/T/ipykernel_72175/175144503.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_cleaned2[col].replace("..", 0, inplace=True)

In [11]:
#Data Cleaning
#Step 6 - Handling outliers

numeric_cols = dataset_cleaned2.select_dtypes(include=['float64', 'int64']).columns

def handle_outliers_iqr(dataset_cleaned2, col):
    Q1 = dataset_cleaned2[col].quantile(0.25)
    Q3 = dataset_cleaned2[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    median_value = dataset_cleaned2[col].median()

    # Replace outliers with the median value using .loc to avoid the warning
    dataset_cleaned2.loc[(dataset_cleaned2[col] < lower_bound) | (dataset_cleaned2[col] > upper_bound), col] = median_value

for col in numeric_cols:
    handle_outliers_iqr(dataset_cleaned2, col)

file_path = '~/Downloads/cleaned_dataset_outliers.csv'
dataset_cleaned2.to_csv(file_path, index=False)

# Display the first few rows of the cleaned dataset
dataset_cleaned2.head()

/var/folders/cl/trqdqljx2hjfbxn58ysk0cyh0000gn/T/ipykernel_72175/367602348.py:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2013.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  dataset_cleaned2.loc[(dataset_cleaned2[col] < lower_bound) | (dataset_cleaned2[col] > upper_bound), col] = median_value

,Region Name,Region Code,Year,"Birth rate, crude (per 1,000 people) [SP.DYN.CBRT.IN]",Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS],"Death rate, crude (per 1,000 people) [SP.DYN.CDRT.IN]","Hospital beds (per 1,000 people) [SH.MED.BEDS.ZS]","Immunization, BCG (% of one-year-old children) [SH.IMM.IBCG]","Immunization, HepB3 (% of one-year-old children) [SH.IMM.HEPB]","Immunization, measles second dose (% of children by the nationally recommended age) [SH.IMM.MEA2]",...,Number of neonatal deaths [SH.DTH.NMRT],Number of stillbirths [SH.DTH.STLB],"Nurses and midwives (per 1,000 people) [SH.MED.NUMW.P3]","Physicians (per 1,000 people) [SH.MED.PHYS.ZS]",Prevalence of anemia among pregnant women (%) [SH.PRG.ANEM],Prevalence of anemia among children (% of children ages 6-59 months) [SH.ANM.CHLD.ZS],"Prevalence of current tobacco use, pregnant women (% of pregnant women adults) [SH.PRV.SMOK.FE]","Prevalence of hypertension, pregnant women (% of pregnant women adults ages 30-79) [SH.HTN.PREV.FE.ZS]","Stillbirth rate (per 1,000 total births) [SH.DYN.STLB]",Vitamin A supplementation coverage rate (% of children ages 6-59 months) [SN.ITK.VITA.ZS]
0,United States,USA,2004.0,14.0,99.3,8.2,3.26,NaN,92.0,86.0,...,18738.0,12822.0,0,2.7,9.1,5.9,0,29.9,3.1,0
1,United States,USA,2005.0,14.0,99.4,8.3,3.2,NaN,93.0,86.0,...,18569.0,12462.0,9.9177,0,9.2,5.9,24.2,30.0,3.0,0
2,United States,USA,2006.0,14.3,99.4,8.1,3.18,NaN,93.0,86.0,...,18817.0,12699.0,0,0,9.3,5.8,0,30.0,3.0,0
3,United States,USA,2007.0,14.3,99.3,8.0,3.14,NaN,93.0,86.0,...,18769.0,12965.0,0,0,9.5,5.8,0,30.1,3.0,0
4,United States,USA,2008.0,14.0,99.3,8.1,3.13,NaN,94.0,87.0,...,18139.0,13204.0,0,0,9.6,5.8,0,30.1,3.1,0

In [12]:
 #Data cleaning
# Step 7 - Handling Negative Values
numeric_cols = dataset_cleaned2.select_dtypes(include=['float64', 'int64']).columns

dataset_cleaned2 = dataset_cleaned2[(dataset_cleaned2[numeric_cols] >= 0).all(axis=1)]

file_path = '~/Downloads/handling_negative_values.csv'
dataset_cleaned2.to_csv(file_path, index=False)

dataset_cleaned2.head()

,Region Name,Region Code,Year,"Birth rate, crude (per 1,000 people) [SP.DYN.CBRT.IN]",Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS],"Death rate, crude (per 1,000 people) [SP.DYN.CDRT.IN]","Hospital beds (per 1,000 people) [SH.MED.BEDS.ZS]","Immunization, BCG (% of one-year-old children) [SH.IMM.IBCG]","Immunization, HepB3 (% of one-year-old children) [SH.IMM.HEPB]","Immunization, measles second dose (% of children by the nationally recommended age) [SH.IMM.MEA2]",...,Number of neonatal deaths [SH.DTH.NMRT],Number of stillbirths [SH.DTH.STLB],"Nurses and midwives (per 1,000 people) [SH.MED.NUMW.P3]","Physicians (per 1,000 people) [SH.MED.PHYS.ZS]",Prevalence of anemia among pregnant women (%) [SH.PRG.ANEM],Prevalence of anemia among children (% of children ages 6-59 months) [SH.ANM.CHLD.ZS],"Prevalence of current tobacco use, pregnant women (% of pregnant women adults) [SH.PRV.SMOK.FE]","Prevalence of hypertension, pregnant women (% of pregnant women adults ages 30-79) [SH.HTN.PREV.FE.ZS]","Stillbirth rate (per 1,000 total births) [SH.DYN.STLB]",Vitamin A supplementation coverage rate (% of children ages 6-59 months) [SN.ITK.VITA.ZS]
86,Albania,ALB,2004.0,13.978,99.3,6.181,3.01,97.0,99.0,96.0,...,469.0,274.0,3.636,1.208,25.8,29.6,0,39.4,6.3,0
87,Albania,ALB,2005.0,13.235,99.8,6.306,3.08,98.0,98.0,97.0,...,425.0,250.0,3.672,0,25.0,28.3,9.4,39.4,6.1,0
88,Albania,ALB,2006.0,12.539,99,6.477,3.12,97.0,98.0,94.0,...,378.0,224.0,4.244,1.207,24.3,27.1,0,39.5,5.9,0
89,Albania,ALB,2007.0,12.070,0,6.318,3.09,98.0,98.0,95.0,...,333.0,201.0,4.283,1.218,23.5,25.9,0,39.7,5.5,0
90,Albania,ALB,2008.0,11.868,0,6.570,0,99.0,99.0,98.0,...,291.0,184.0,0,0,22.9,24.8,0,39.8,5.2,0

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
#Data cleaning
#Step 8 - Standardizing Categorical Data
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

dataset_cleaned2['Region Code Numeric'] = label_encoder.fit_transform(dataset_cleaned2['Region Code'])
region_code_mapping = dict(zip(label_encoder.classes_, range(len(label_encoder.classes_))))

print("Region Code Mapping:")
print(region_code_mapping)

file_path = '~/Downloads/standardized_region_code.csv'
dataset_cleaned2.to_csv(file_path, index=False)

# Display the first few rows of the updated dataset
print(dataset_cleaned2.head())

Region Code Mapping:
{'AGO': 0, 'ALB': 1, 'ARE': 2, 'ARG': 3, 'ARM': 4, 'AZE': 5, 'BDI': 6, 'BFA': 7, 'BGD': 8, 'BGR': 9, 'BIH': 10, 'BLR': 11, 'BLZ': 12, 'BOL': 13, 'BRA': 14, 'BRN': 15, 'BTN': 16, 'BWA': 17, 'CHL': 18, 'CHN': 19, 'COG': 20, 'COL': 21, 'CRI': 22, 'CUB': 23, 'CZE': 24, 'DOM': 25, 'DZA': 26, 'EAP': 27, 'EAS': 28, 'ECA': 29, 'ECU': 30, 'ERI': 31, 'EST': 32, 'FJI': 33, 'GEO': 34, 'GHA': 35, 'GMB': 36, 'GTM': 37, 'GUY': 38, 'HND': 39, 'HRV': 40, 'IDN': 41, 'IND': 42, 'IRQ': 43, 'JAM': 44, 'JOR': 45, 'JPN': 46, 'KAZ': 47, 'KEN': 48, 'KGZ': 49, 'KHM': 50, 'KIR': 51, 'KOR': 52, 'KWT': 53, 'LAC': 54, 'LAO': 55, 'LBR': 56, 'LCA': 57, 'LCN': 58, 'LKA': 59, 'LSO': 60, 'LTU': 61, 'LVA': 62, 'MAR': 63, 'MDA': 64, 'MDV': 65, 'MEX': 66, 'MIC': 67, 'MKD': 68, 'MMR': 69, 'MNE': 70, 'MNG': 71, 'MOZ': 72, 'MUS': 73, 'MWI': 74, 'MYS': 75, 'NAM': 76, 'NIC': 77, 'NPL': 78, 'OMN': 79, 'PAN': 80, 'PER': 81, 'PHL': 82, 'PNG': 83, 'PRT': 84, 'PRY': 85, 'PSS': 86, 'QAT': 87, 'ROU': 88, 'RUS': 89, 'RWA': 90, 'SAS': 91, 'SEN': 92, 'SGP': 93, 'SLB': 94, 'SLE': 95, 'SLV': 96, 'SRB': 97, 'SST': 98, 'STP': 99, 'SVK': 100, 'SWE': 101, 'SWZ': 102, 'SYC': 103, 'TEA': 104, 'TEC': 105, 'TGO': 106, 'THA': 107, 'TJK': 108, 'TKM': 109, 'TLA': 110, 'TLS': 111, 'TUN': 112, 'TZA': 113, 'UKR': 114, 'URY': 115, 'UZB': 116, 'VEN': 117, 'VNM': 118, 'ZAF': 119, 'ZMB': 120, 'ZWE': 121}
   Region Name Region Code    Year  \
86     Albania         ALB  2004.0
87     Albania         ALB  2005.0
88     Albania         ALB  2006.0
89     Albania         ALB  2007.0
90     Albania         ALB  2008.0

    Birth rate, crude (per 1,000 people) [SP.DYN.CBRT.IN]  \
86                                             13.978
87                                             13.235
88                                             12.539
89                                             12.070
90                                             11.868

   Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS]  \
86                                               99.3
87                                               99.8
88                                                 99
89                                                  0
90                                                  0

    Death rate, crude (per 1,000 people) [SP.DYN.CDRT.IN]  \
86                                              6.181
87                                              6.306
88                                              6.477
89                                              6.318
90                                              6.570

   Hospital beds (per 1,000 people) [SH.MED.BEDS.ZS]  \
86                                              3.01
87                                              3.08
88                                              3.12
89                                              3.09
90                                                 0

    Immunization, BCG (% of one-year-old children) [SH.IMM.IBCG]  \
86                                               97.0
87                                               98.0
88                                               97.0
89                                               98.0
90                                               99.0

    Immunization, HepB3 (% of one-year-old children) [SH.IMM.HEPB]  \
86                                               99.0
87                                               98.0
88                                               98.0
89                                               98.0
90                                               99.0

    Immunization, measles second dose (% of children by the nationally recommended age) [SH.IMM.MEA2]  \
86                                               96.0
87                                               97.0
88                                               94.0
89                                               95.0
90                                               98.0

    ...  Number of stillbirths [SH.DTH.STLB]  \
86  ...                                274.0
87  ...                                250.0
88  ...                                224.0
89  ...                                201.0
90  ...                                184.0

    Nurses and midwives (per 1,000 people) [SH.MED.NUMW.P3]  \
86                                              3.636
87                                              3.672
88                                              4.244
89                                              4.283
90                                                  0

    Physicians (per 1,000 people) [SH.MED.PHYS.ZS]  \
86                                           1.208
87                                               0
88                                           1.207
89                                           1.218
90                                               0

    Prevalence of anemia among pregnant women (%) [SH.PRG.ANEM]  \
86                                               25.8
87                                               25.0
88                                               24.3
89                                               23.5
90                                               22.9

    Prevalence of anemia among children (% of children ages 6-59 months) [SH.ANM.CHLD.ZS]  \
86                                               29.6
87                                               28.3
88                                               27.1
89                                               25.9
90                                               24.8

    Prevalence of current tobacco use, pregnant women (% of pregnant women adults) [SH.PRV.SMOK.FE]  \
86                                                  0
87                                                9.4
88                                                  0
89                                                  0
90                                                  0

   Prevalence of hypertension, pregnant women (% of pregnant women adults ages 30-79) [SH.HTN.PREV.FE.ZS]  \
86                                               39.4
87                                               39.4
88                                               39.5
89                                               39.7
90                                               39.8

   Stillbirth rate (per 1,000 total births) [SH.DYN.STLB]  \
86                                                6.3
87                                                6.1
88                                                5.9
89                                                5.5
90                                                5.2

    Vitamin A supplementation coverage rate (% of children ages 6-59 months) [SN.ITK.VITA.ZS]  \
86                                                  0
87                                                  0
88                                                  0
89                                                  0
90                                                  0

    Region Code Numeric
86                    1
87                    1
88                    1
89                    1
90                    1

[5 rows x 41 columns]

In [15]:
import re

In [16]:
beautify_data = dataset_cleaned2.head(100)

numeric_cols = beautify_data.select_dtypes(include=['number'])

styled_data = beautify_data.style.set_properties(**{
    'border': '1px solid black',
    'color': 'black',
    'background-color': '#f4f4f9',
    'text-align': 'center',
}).set_table_styles([{
    'selector': 'thead th',
    'props': [('background-color', '#55608f'), ('color', 'white'), ('font-size', '12px')]
}])

styled_data = styled_data.highlight_max(subset=numeric_cols.columns, color='lightgreen').highlight_min(subset=numeric_cols.columns, color='lightcoral')

from IPython.display import display

display(styled_data)